# Generated by Django 5.2.4 on 2025-07-23 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Температура на складе')),
                ('ceilings', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Высота потолка')),
                ('advantage', models.CharField(blank=True, choices=[('parking', 'Парковка'), ('metro', 'Рядом с метро'), ('ceilings', 'Высокие потолки'), ('box', 'Большие боксы')], max_length=100, null=True, verbose_name='Преимущество склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('square', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена аренды')),
                ('is_free', models.BooleanField(blank=True, default=True, null=True, verbose_name='Бокс свободен')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage_units.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
    ]
