# Generated by Django 5.2.4 on 2025-07-26 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тарифа"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена в месяц (руб.)",
                    ),
                ),
                (
                    "min_square_meters",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Минимальная площадь бокса (м²)",
                    ),
                ),
                (
                    "max_square_meters",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальная площадь бокса (м²)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Подробное описание тарифа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ["min_square_meters", "price"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название склада"),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото склада"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Температура на складе",
                    ),
                ),
                (
                    "ceilings",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Высота потолка"
                    ),
                ),
                (
                    "advantage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ceilings", "Высокие потолки"),
                            ("parking", "Парковка"),
                            ("box", "Большие боксы"),
                            ("metro", "Рядом с метро"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Преимущество склада",
                    ),
                ),
                (
                    "is_default_nearest",
                    models.BooleanField(
                        default=False, verbose_name="Ближайший склад по умолчанию"
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Этаж",
                    ),
                ),
                (
                    "length",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Длина",
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Высота",
                    ),
                ),
                (
                    "square",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Площадь",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена аренды"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        null=True,
                        verbose_name="Бокс свободен",
                    ),
                ),
                (
                    "paid_for",
                    models.DateField(blank=True, null=True, verbose_name="Оплачен до"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rent_boxes",
                        to="orders.client",
                        verbose_name="Арендатор",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="storage_units.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бокс",
                "verbose_name_plural": "Боксы",
            },
        ),
    ]
