# Generated by Django 4.2.23 on 2025-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_default_nearest',
            field=models.BooleanField(default=False, verbose_name='Ближайший склад по умолчанию'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='advantage',
            field=models.CharField(blank=True, choices=[('box', 'Большие боксы'), ('metro', 'Рядом с метро'), ('parking', 'Парковка'), ('ceilings', 'Высокие потолки')], max_length=100, null=True, verbose_name='Преимущество склада'),
        ),
    ]
