# Generated by Django 4.2.23 on 2025-07-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='advantage',
            field=models.CharField(blank=True, choices=[('metro', 'Рядом с метро'), ('box', 'Большие боксы'), ('parking', 'Парковка'), ('ceilings', 'Высокие потолки')], max_length=100, null=True, verbose_name='Преимущество склада'),
        ),
    ]
