# Generated by Django 5.2.4 on 2025-07-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_units", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="advantage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ceilings", "Высокие потолки"),
                    ("parking", "Парковка"),
                    ("box", "Большие боксы"),
                    ("metro", "Рядом с метро"),
                ],
                max_length=100,
                null=True,
                verbose_name="Преимущество склада",
            ),
        ),
    ]
