# Generated by Django 5.2.4 on 2025-07-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage_units", "0002_alter_warehouse_advantage"),
        ("storage_units", "0002_warehouse_is_default_nearest_and_more"),
    ]

    operations = []
